### ISSUE TITLE
Set up the Project Kanban Board

### ISSUE THREAD

**Issue by momo-87** [momo-87/recipe-app#16]
Below is the link to the project Kanban board:
https://github.com/users/momo-87/projects/6/views/1

We are two in this Ruby on Rails project:

1. Christian Romulad Momo Tonfack
2. Salomon Tsobohwa

**Comment by Davidosky007** [comment]
Hi @momo-87 @Tshobohwa 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a broken Kanban board link kindly add a working link

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Olamarx** [comment]
Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/WOTMeqMcNkLuXibbKz/giphy.gif"/>

## Highlights
- Good use of Kanban board ✔️
- Fair distribution ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I can see that you are yet to add some tasks to your board such as the Food list, Recipe list and others, kindly ensure all are added as it is in the attached project requirement.
![image](https://github.com/momo-87/recipe-app/assets/86200356/9a0ec1a6-7388-4f92-a60b-5374bbcf9a31)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @momo-87 and @Tshobohwa,

✔️ Tasks are well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
